name: Component Test Suite

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  unit-test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm run test # Run unit tests
